// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/source-map-support/source-map-support.d.ts
declare module 'source-map-support' {
	/**
	 * Output of retrieveSourceMap().
	 */
	export interface UrlAndMap {
		url: string;
		map: string|Buffer;
	}

	/**
	 * Options to install().
	 */
	export interface Options {
		handleUncaughtExceptions?: boolean;
		emptyCacheBetweenOperations?: boolean;
		retrieveFile?: (path: string) => string;
		retrieveSourceMap?: (source: string) => UrlAndMap;
	}

	export interface Position {
		source: string;
		line: number;
		column: number;
	}

	export function wrapCallSite(frame: any /* StackFrame */): any /* StackFrame */;
	export function getErrorSource(error: Error): string;
	export function mapSourcePosition(position: Position): Position;
	export function retrieveSourceMap(source: string): UrlAndMap;

	/**
	 * Install SourceMap support.
	 * @param options Can be used to e.g. disable uncaughtException handler.
	 */
	export function install(options?: Options): void;
}
